# Generated by Django 6.0.5 on 2026-06-27 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(db_index=True, max_length=36)),
                ('quality', models.CharField(max_length=16)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('chapter_id', 'quality'), name='uniq_chapter_ingestion_chapter_quality')],
            },
        ),
        migrations.CreateModel(
            name='StoredPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveIntegerField()),
                ('panel_index', models.PositiveIntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('byte_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(default='image/avif', max_length=64)),
                ('public_url', models.URLField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='api.chapteringestion')),
            ],
            options={
                'ordering': ['page_index', 'panel_index'],
                'constraints': [models.UniqueConstraint(fields=('chapter', 'page_index', 'panel_index'), name='uniq_stored_panel_chapter_page_panel')],
            },
        ),
    ]
