# Generated by Django 6.0.5 on 2026-06-29 04:54

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name='storedpanel',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
    ]
