# Generated by Django 6.0.5 on 2026-09-27 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_panelsubelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedpanel",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="panelsubelement",
            name="label",
            field=models.CharField(
                choices=[
                    ("face", "face"),
                    ("eyes", "eyes"),
                    ("hand", "hand"),
                    ("person", "person"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="PanelTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=128)),
                ("score", models.FloatField(default=0.0)),
                ("source", models.CharField(default="panel", max_length=16)),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_rows",
                        to="api.storedpanel",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tag", "score"], name="api_panelta_tag_802f54_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("panel", "tag"), name="uniq_panel_tag"
                    )
                ],
            },
        ),
    ]
