"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-(ebvdrkd5%koioe67a_d(s=nf%o-#g@qo^+nh^_5^dde4x%!70",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


def _postgres_config(
    name: str,
    user: str,
    password: str,
    host: str,
    port: str,
    *,
    sslmode_from_url: str | None = None,
) -> dict:
    """Build Django PostgreSQL settings; SSL required for Supabase unless overridden."""
    cfg: dict = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": port,
    }
    sslmode = (sslmode_from_url or "").strip().lower()
    if not sslmode:
        sslmode = os.getenv("POSTGRES_SSLMODE", "").strip().lower()
    if not sslmode and "supabase" in host.lower():
        sslmode = "require"
    if sslmode:
        cfg["OPTIONS"] = {"sslmode": sslmode}
    return cfg


def _postgres_from_database_url(url: str) -> dict:
    parsed = urlparse(url)
    scheme = (parsed.scheme or "").lower()
    if scheme not in ("postgres", "postgresql"):
        raise ValueError(
            "DATABASE_URL must start with postgres:// or postgresql://"
        )
    db_name = (parsed.path or "").lstrip("/") or "postgres"
    user = unquote(parsed.username or "")
    password = unquote(parsed.password or "")
    host = parsed.hostname or "localhost"
    port = str(parsed.port or 5432)
    ssl_params = parse_qs(parsed.query).get("sslmode") or []
    url_ssl = ssl_params[0].strip() if ssl_params and ssl_params[0].strip() else None
    return _postgres_config(
        db_name, user, password, host, port, sslmode_from_url=url_ssl
    )


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_database_url = os.getenv("DATABASE_URL", "").strip()
_postgres_db = os.getenv("POSTGRES_DB", "").strip()

if _database_url:
    DATABASES = {"default": _postgres_from_database_url(_database_url)}
elif _postgres_db:
    DATABASES = {
        "default": _postgres_config(
            _postgres_db,
            os.getenv("POSTGRES_USER", ""),
            os.getenv("POSTGRES_PASSWORD", ""),
            os.getenv("POSTGRES_HOST", "localhost"),
            os.getenv("POSTGRES_PORT", "5432"),
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Amazon S3 (consumed when you wire storage clients, e.g. boto3)
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
# Optional: CloudFront or static website / virtual-hosted URL base for public URLs returned to the frontend
AWS_S3_PUBLIC_BASE_URL = os.getenv("AWS_S3_PUBLIC_BASE_URL", "").rstrip("/")

# Image compression
TINIFY_API_KEY = os.getenv("TINIFY_API_KEY", "")
IMAGE_JPEG_QUALITY = int(os.getenv("IMAGE_JPEG_QUALITY", "85"))
IMAGE_AVIF_QUALITY = int(os.getenv("IMAGE_AVIF_QUALITY", "50"))
IMAGE_MAX_EDGE_PX = int(os.getenv("IMAGE_MAX_EDGE_PX", "2048"))

# Web scraping
SCRAPER_USER_AGENT = os.getenv(
    "SCRAPER_USER_AGENT",
    "MangaIndexer/0.1 (+https://example.com/contact)",
)
SCRAPER_REQUEST_TIMEOUT = int(os.getenv("SCRAPER_REQUEST_TIMEOUT", "30"))
SCRAPER_PROXY_URL = os.getenv("SCRAPER_PROXY_URL", "")
SCRAPER_ZENROWS_API_KEY = os.getenv("SCRAPER_ZENROWS_API_KEY", "")

# Embeddings
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN", "")
EMBEDDING_DEVICE = os.getenv("EMBEDDING_DEVICE", "cpu")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
